# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Smart Motorways' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smart Motorways
  pod 'Alamofire', '~> 5.2'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'ImageSlideshow', '~> 1.9.0'
  pod 'NVActivityIndicatorView'
  pod "MediaWatermark"
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'


  target 'Smart MotorwaysTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Smart MotorwaysUITests' do
    # Pods for testing
  end

end
